//ignore this file. This is for my reference only.

//date
import dayjs from 'dayjs';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';

import Button from '@mui/material/Button';
import FormControl from '@mui/material/FormControl';
import Grid from '@mui/material/Grid';
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';
import Select from '@mui/material/Select';
import TextField from '@mui/material/TextField';
import Typography from '@mui/material/Typography';

//error display
import Alert from '@mui/material/Alert';
import AlertTitle from '@mui/material/AlertTitle';


export function CreateJobForm({ jobs, setJobs }) {
  //We will function to deal with the information being passed into the form that the return statement generated below. These include ones that will handle the information from event object generated by the form submission, such as the title, company name, etc to create a new object that will be passed into the RecentlyCreatedJob.js to generate new jobs on the frontend.

  //first, let's initialize values for all of the key-value pairs inside the object that we'll be creating. Making these into their own function allows us to useState to overwrite them later; main purpose is to allows us to attach them to the form and seamlessly pull them for our handleSubmit function. 

  const [jobTitle, setJobTitle] = useState('');
  const [companyTitle, setCompanyTitle] = useState('');
  const [jobDescription, setDescription] = useState('');
  const [jobLocation, setLocation] = useState('');
  const [jobType, setJobType] = useState('');
  const [jobQualifications, setQualifications] = useState('');
  const [datePosted, setDatePosted] = useState(dayjs(Date.now));
  const [error, setError] = useState('');

  const handleSubmit = (event) => {
    
    try {
    event.preventDefault();
    validateForm();
    let createObjectAndAddToJobs = [
      {
        title: jobTitle,
        description: jobDescription,
        location: jobLocation,
        job_type: jobType,
        qualifications: jobQualifications,
        company_name: companyTitle,
        date_posted: datePosted.format('YYYY-MM-DD')
        //create A new object [job] 
      },
      ...jobs //add this job to the array with existing and previous jobs
    ]
    setJobs(createObjectAndAddToJobs); //now createObjectAndAddToJobs has the object just put in through the form and the previous jobs
    resetForm(); //now erase values to start fresh
  } catch(error) {
    setError(error.message)
  }
}

  const resetForm = () => {
    setJobTitle('')
    setDatePosted(dayjs(Date.now()))
    setCompanyTitle('')
    setJobType('')
    setLocation('')
    setDescription('')    
    setQualifications('')
  }

  const validateForm = () => {
    setError("");
    let errorMessage = '';
    if (jobTitle.trim().length <= 9) {
      errorMessage += "- Title must be at least 10 characters\n"
    }
    if (![
      "Full-Time",
      "Part-Time",
      "Contract"
    ].includes(jobType)) {
      errorMessage += "- Type must be one of the following: Full-time, Part-time, Contract\n" // \n = insert new line
    }
    if (datePosted.isBefore(dayjs(Date.now()), 'day')) {
      errorMessage += "- Date Posted must be in the future\n"
    } 
    if (companyTitle.trim().length === 0) {
      errorMessage += "- Company Name is required\n"
    } //=== because we are not assigning, just comparing
    if (jobLocation.trim().length === 0) {
      errorMessage += "- Location is required\n"
    }
    if (jobDescription.trim().length === 0) {
      errorMessage += "- Description is required\n"
    }
     if (jobQualifications.trim().length === 0) {
      errorMessage += "- Qualifications are required"
    }
    if (errorMessage != ''){
      throw new Error(errorMessage)
    }
  }

  
  
  
  
  
  return <form onSubmit={handleSubmit}>
    <Typography
      variant="h4"
      sx={{ paddingTop: 2, paddingBottom: 2}}
    >
      Post a New Job 
    </Typography>
    <Grid container spacing={2}>
      <Grid item xs={6}>
        <TextField
          label="Job Title"
          fullWidth
          sx={{width: '80%'}}
          value={jobTitle}
          onChange={(event) => {
            setJobTitle(event.target.value);
            console.log('jobTitle = ' + event.target.value); // at this point, jobTitle becomes whatever is typed 
          }

          }
        />
      </Grid>
      <Grid item xs={6}>
      <LocalizationProvider dateAdapter={AdapterDayjs}>
        <DatePicker
          label="Date Posted"
          defaultValue={dayjs(Date.now())}
          value={datePosted}
          sx={{width: '80%'}}  
          onChange={(newValue) => {
            setDatePosted(newValue);
            console.log('date posted =', newValue);
            //can't use event.target.value probably bc of the date selection method
          }}
        /> 
        </LocalizationProvider>
      </Grid>
      <Grid item xs={6}>
        <TextField
          label="Company Name"
          fullWidth
          sx={{width: '80%'}}
          value={companyTitle}
          onChange={(event) => {
            setCompanyTitle(event.target.value);
            console.log('company title=' + event.target.value);
          }}
        />
      </Grid>
      <Grid item xs={6}>
        <FormControl fullWidth>
          <InputLabel id="job-type-select">Job Type</InputLabel>
          <Select
              labelId="job-type-select"
              label="Job Type"
              value={jobType}
              sx={{width: '80%'}}
              onChange={(event) => {
            setJobType(event.target.value);
            console.log('job type =', event.target.value); // values are updating one word/stoke/select less at a time on the console b/c jobType doesn't update the value fast enough.
          }}>
            <MenuItem value={"Full-Time"}>Full-Time</MenuItem>
            <MenuItem value={"Part-Time"}>Part-Time</MenuItem>
            <MenuItem value={"Contract"}>Contract</MenuItem>
          </Select>
        </FormControl>
      </Grid>
      <Grid item xs={6}>
        <TextField
          label="Location"
          value={jobLocation}
          fullWidth
          sx={{width: '80%'}}
          onChange={(event) => {
            setLocation(event.target.value);
            console.log('location', event.target.value);
          }}
        />
      </Grid>
      <Grid item xs={12}>
        <TextField
          label="Description"
          fullWidth
          sx={{width: '90%'}}
          multiline
          rows={2}
          value={jobDescription}
          onChange={(event) => {
            setDescription(event.target.value);
            console.log('description =' + event.target.value);
          }}
        />
      </Grid>
      <Grid item xs={12}>
        <TextField
          label="Qualifications"
          fullWidth
          sx={{width: '90%'}}
          multiline
          rows={2}
          value={jobQualifications}
          onChange={(event) => {
            setQualifications(event.target.value);
            console.log('qualifications =' + event.target.value);
          }}
        />
      </Grid>
      <Grid item xs={12}>

        <Button variant="contained" type="submit">Submit new Job</Button>
      </Grid>
       <Grid item xs={12}>
          {error && <Alert severity="error">
            <AlertTitle>Validation Error</AlertTitle>
            <div style={{whiteSpace: 'pre-line'}}>{error}</div>
          </Alert>}
        </Grid>
    </Grid>
  </form>
} 
